# from https://github.com/flaiker/ci-cfg-templates/blob/master/travis-ci/libgdx.travis.yml

language: android # can be 'java' if there is no android build target
android:
  components:
    - build-tools-20.0.0
    - android-20
jdk: oraclejdk8

# Cache gradle dependencies (should be faster to download them from cache)
cache:
  directories:
    - $HOME/.gradle/wrapper
    - $HOME/.gradle/caches/modules-2/files-2.1

# Gross workaround for builds failing: https://github.com/travis-ci/travis-ci/issues/8874
before_install:
  - yes | sdkmanager "platforms;android-27"
